# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ApeiOneShotResult.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ApeiOneShotResult.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x41peiOneShotResult.proto\x12\"com.arashivision.arvbmg.apei.proto\">\n\x04View\x12\x10\n\x08\x66rame_id\x18\x01 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x02 \x03(\x01\x12\x16\n\x0e\x64\x65\x64uplication_\x18\x03 \x01(\x05\"R\n\x05Track\x12\x10\n\x08track_id\x18\x01 \x01(\x05\x12\x37\n\x05views\x18\x02 \x03(\x0b\x32(.com.arashivision.arvbmg.apei.proto.View\"\\\n\x10\x41peiOneShotRatio\x12\r\n\x05ratio\x18\x01 \x01(\x05\x12\x39\n\x06tracks\x18\x02 \x03(\x0b\x32).com.arashivision.arvbmg.apei.proto.Track\"Y\n\x11\x41peiOneShotResult\x12\x44\n\x06ratios\x18\x01 \x03(\x0b\x32\x34.com.arashivision.arvbmg.apei.proto.ApeiOneShotRatioB\x08\xa2\x02\x05INSPBb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ApeiOneShotResult_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\242\002\005INSPB'
  _globals['_VIEW']._serialized_start=63
  _globals['_VIEW']._serialized_end=125
  _globals['_TRACK']._serialized_start=127
  _globals['_TRACK']._serialized_end=209
  _globals['_APEIONESHOTRATIO']._serialized_start=211
  _globals['_APEIONESHOTRATIO']._serialized_end=303
  _globals['_APEIONESHOTRESULT']._serialized_start=305
  _globals['_APEIONESHOTRESULT']._serialized_end=394
# @@protoc_insertion_point(module_scope)
