# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ApeiModelResult.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ApeiModelResult.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x41peiModelResult.proto\x12\"com.arashivision.arvbmg.apei.proto\"d\n\x0f\x41peiModelResult\x12\x0e\n\x06labels\x18\x01 \x01(\x05\x12\x0e\n\x06scores\x18\x02 \x01(\x01\x12\x13\n\x0bview_scores\x18\x03 \x01(\x01\x12\r\n\x05\x61ttrs\x18\x04 \x03(\x01\x12\r\n\x05sfovs\x18\x05 \x03(\x01\"\x9c\x01\n\x12\x41peiFrontEndResult\x12@\n\tvideoInfo\x18\x01 \x01(\x0b\x32-.com.arashivision.arvbmg.apei.proto.VideoInfo\x12\x44\n\tresultMap\x18\x02 \x01(\x0b\x32\x31.com.arashivision.arvbmg.apei.proto.ApeiResultMap\"I\n\tVideoInfo\x12\x17\n\x0ftotalFrameCount\x18\x01 \x01(\x05\x12\x10\n\x08videoFps\x18\x02 \x01(\x05\x12\x11\n\tsampleFps\x18\x03 \x01(\x05\"\x7f\n\rApeiResultMap\x12\x44\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x33.com.arashivision.arvbmg.apei.proto.ApeiResultEntry\x12\x15\n\rmodel_version\x18\x02 \x01(\t\x12\x11\n\tcome_from\x18\x03 \x01(\x05\"b\n\x0f\x41peiResultEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\x42\n\x05value\x18\x02 \x03(\x0b\x32\x33.com.arashivision.arvbmg.apei.proto.ApeiModelResultB\x08\xa2\x02\x05INSPBb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ApeiModelResult_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\242\002\005INSPB'
  _globals['_APEIMODELRESULT']._serialized_start=61
  _globals['_APEIMODELRESULT']._serialized_end=161
  _globals['_APEIFRONTENDRESULT']._serialized_start=164
  _globals['_APEIFRONTENDRESULT']._serialized_end=320
  _globals['_VIDEOINFO']._serialized_start=322
  _globals['_VIDEOINFO']._serialized_end=395
  _globals['_APEIRESULTMAP']._serialized_start=397
  _globals['_APEIRESULTMAP']._serialized_end=524
  _globals['_APEIRESULTENTRY']._serialized_start=526
  _globals['_APEIRESULTENTRY']._serialized_end=624
# @@protoc_insertion_point(module_scope)
