# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auto_find.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'auto_find.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import auto_find_info_pb2 as auto__find__info__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x61uto_find.proto\x12\x11insta360.messages\x1a\x14\x61uto_find_info.proto\"\\\n\x08\x41utoFind\x12\x0e\n\x06isYFov\x18\x01 \x01(\x08\x12\x0e\n\x06\x61spect\x18\x02 \x01(\x01\x12\x30\n\nlayer_info\x18\x03 \x01(\x0b\x32\x1c.insta360.messages.LayerInfoB\x08\xa2\x02\x05INSPBb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auto_find_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\242\002\005INSPB'
  _globals['_AUTOFIND']._serialized_start=60
  _globals['_AUTOFIND']._serialized_end=152
# @@protoc_insertion_point(module_scope)
