# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auto_find_info.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'auto_find_info.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x61uto_find_info.proto\x12\x11insta360.messages\"\xe6\x05\n\tLayerInfo\x12\x0f\n\x07version\x18\x01 \x01(\t\x12\x18\n\x10order_of_targets\x18\x02 \x03(\t\x12\x41\n\x0bmap_targets\x18\x03 \x03(\x0b\x32,.insta360.messages.LayerInfo.MapTargetsEntry\x12\x36\n\x06states\x18\x04 \x03(\x0b\x32&.insta360.messages.LayerInfo.StateInfo\x12@\n\x0btransitions\x18\x05 \x03(\x0b\x32+.insta360.messages.LayerInfo.TransitionInfo\x12\x1a\n\x12start_timestamp_ms\x18\x06 \x01(\x01\x12\x18\n\x10\x65nd_timestamp_ms\x18\x07 \x01(\x01\x1aZ\n\x0fMapTargetsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x36\n\x05value\x18\x02 \x01(\x0b\x32\'.insta360.messages.LayerInfo.TargetInfo:\x02\x38\x01\x1a\x8a\x01\n\tStateInfo\x12\x0e\n\x06target\x18\x01 \x01(\t\x12\x0b\n\x03\x66ov\x18\x02 \x01(\x05\x12\x10\n\x08\x64istance\x18\x03 \x01(\x05\x12\x12\n\ntime_ratio\x18\x04 \x01(\x02\x12\x10\n\x08\x66rame_id\x18\x05 \x01(\t\x12\x0b\n\x03yaw\x18\x06 \x01(\x02\x12\r\n\x05pitch\x18\x07 \x01(\x02\x12\x0c\n\x04roll\x18\x08 \x01(\x02\x1aJ\n\x0eTransitionInfo\x12\x0c\n\x04\x66unc\x18\x01 \x01(\t\x12\x15\n\rfrom_state_id\x18\x02 \x01(\t\x12\x13\n\x0bto_state_id\x18\x03 \x01(\t\x1a\x85\x01\n\nTargetInfo\x12\x10\n\x08\x66rame_id\x18\x01 \x01(\t\x12\x12\n\nfov_target\x18\x02 \x01(\x05\x12\x12\n\ndis_target\x18\x03 \x01(\x05\x12\x12\n\nyaw_target\x18\x04 \x01(\x05\x12\x14\n\x0cpitch_target\x18\x05 \x01(\x05\x12\x13\n\x0broll_target\x18\x06 \x01(\x05\x42\x08\xa2\x02\x05INSPBb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auto_find_info_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\242\002\005INSPB'
  _globals['_LAYERINFO_MAPTARGETSENTRY']._loaded_options = None
  _globals['_LAYERINFO_MAPTARGETSENTRY']._serialized_options = b'8\001'
  _globals['_LAYERINFO']._serialized_start=44
  _globals['_LAYERINFO']._serialized_end=786
  _globals['_LAYERINFO_MAPTARGETSENTRY']._serialized_start=343
  _globals['_LAYERINFO_MAPTARGETSENTRY']._serialized_end=433
  _globals['_LAYERINFO_STATEINFO']._serialized_start=436
  _globals['_LAYERINFO_STATEINFO']._serialized_end=574
  _globals['_LAYERINFO_TRANSITIONINFO']._serialized_start=576
  _globals['_LAYERINFO_TRANSITIONINFO']._serialized_end=650
  _globals['_LAYERINFO_TARGETINFO']._serialized_start=653
  _globals['_LAYERINFO_TARGETINFO']._serialized_end=786
# @@protoc_insertion_point(module_scope)
