# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auto_clip_pano_animation.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'auto_clip_pano_animation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import section_pb2 as section__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x61uto_clip_pano_animation.proto\x12\x11insta360.messages\x1a\rsection.proto\"\xc9\x02\n\x15\x41utoClipPanoAnimation\x12Q\n\x10section_wrap_map\x18\x01 \x03(\x0b\x32\x37.insta360.messages.AutoClipPanoAnimation.SectionWrapMap\x1ai\n\x0eSectionWrapMap\x12\x0b\n\x03key\x18\x01 \x01(\t\x12J\n\x0csection_wrap\x18\x02 \x01(\x0b\x32\x34.insta360.messages.AutoClipPanoAnimation.SectionWrap\x1ar\n\x0bSectionWrap\x12+\n\x07section\x18\x01 \x01(\x0b\x32\x1a.insta360.messages.Section\x12\x36\n\x12section_with_trans\x18\x02 \x01(\x0b\x32\x1a.insta360.messages.SectionB\x08\xa2\x02\x05INSPBb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auto_clip_pano_animation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\242\002\005INSPB'
  _globals['_AUTOCLIPPANOANIMATION']._serialized_start=69
  _globals['_AUTOCLIPPANOANIMATION']._serialized_end=398
  _globals['_AUTOCLIPPANOANIMATION_SECTIONWRAPMAP']._serialized_start=177
  _globals['_AUTOCLIPPANOANIMATION_SECTIONWRAPMAP']._serialized_end=282
  _globals['_AUTOCLIPPANOANIMATION_SECTIONWRAP']._serialized_start=284
  _globals['_AUTOCLIPPANOANIMATION_SECTIONWRAP']._serialized_end=398
# @@protoc_insertion_point(module_scope)
