# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: basic_info.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'basic_info.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x62\x61sic_info.proto\x12\x11insta360.messages\"\\\n\nObjectInfo\x12\x12\n\ntime_ratio\x18\x01 \x01(\x02\x12\x10\n\x08\x66rame_id\x18\x02 \x01(\t\x12\x0b\n\x03yaw\x18\x03 \x01(\x02\x12\r\n\x05pitch\x18\x04 \x01(\x02\x12\x0c\n\x04roll\x18\x05 \x01(\x02\"_\n\nCameraInfo\x12\x0b\n\x03\x66ov\x18\x01 \x01(\x02\x12\x10\n\x08\x64istance\x18\x02 \x01(\x02\x12\x32\n\x0bobject_info\x18\x03 \x01(\x0b\x32\x1d.insta360.messages.ObjectInfo\"J\n\x0eTransitionInfo\x12\x0c\n\x04\x66unc\x18\x01 \x01(\t\x12\x15\n\rfrom_state_id\x18\x02 \x01(\t\x12\x13\n\x0bto_state_id\x18\x03 \x01(\t\"\x99\x01\n\x0b\x42\x65zierCubic\x12\x15\n\rfrom_state_id\x18\x01 \x01(\t\x12\x13\n\x0bto_state_id\x18\x02 \x01(\t\x12\x16\n\x0e\x62\x61zier_ctrl_x1\x18\x03 \x01(\x01\x12\x16\n\x0e\x62\x61zier_ctrl_y1\x18\x04 \x01(\x01\x12\x16\n\x0e\x62\x61zier_ctrl_x2\x18\x05 \x01(\x01\x12\x16\n\x0e\x62\x61zier_ctrl_y2\x18\x06 \x01(\x01\";\n\x0f\x41lphaTransition\x12\x10\n\x08\x64uration\x18\x01 \x01(\x01\x12\x16\n\x0etransitionFile\x18\x02 \x01(\tB\x08\xa2\x02\x05INSPBb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'basic_info_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\242\002\005INSPB'
  _globals['_OBJECTINFO']._serialized_start=39
  _globals['_OBJECTINFO']._serialized_end=131
  _globals['_CAMERAINFO']._serialized_start=133
  _globals['_CAMERAINFO']._serialized_end=228
  _globals['_TRANSITIONINFO']._serialized_start=230
  _globals['_TRANSITIONINFO']._serialized_end=304
  _globals['_BEZIERCUBIC']._serialized_start=307
  _globals['_BEZIERCUBIC']._serialized_end=460
  _globals['_ALPHATRANSITION']._serialized_start=462
  _globals['_ALPHATRANSITION']._serialized_end=521
# @@protoc_insertion_point(module_scope)
