# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: CubePlaylist.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'CubePlaylist.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x43ubePlaylist.proto\x12\x03\x62mg\"&\n\nAVRational\x12\x0b\n\x03num\x18\x01 \x01(\x05\x12\x0b\n\x03\x64\x65n\x18\x02 \x01(\x05\"f\n\x13\x44ynsVideoLayerTiled\x12\x12\n\nresizeRate\x18\x01 \x01(\t\x12\x14\n\x0csliceGridCol\x18\x02 \x01(\x05\x12\x14\n\x0csliceGridRow\x18\x03 \x01(\x05\x12\x0f\n\x07\x62itrate\x18\x04 \x01(\x03\"^\n\x14\x44ynsVideoLayerNormal\x12\x16\n\x0eprojectionType\x18\x01 \x01(\x05\x12\r\n\x05width\x18\x02 \x01(\x05\x12\x0e\n\x06height\x18\x03 \x01(\x05\x12\x0f\n\x07\x62itrate\x18\x04 \x01(\x03\"\x9a\x01\n\x0f\x42\x61seVideoConfig\x12\x11\n\tenableEac\x18\x01 \x01(\x08\x12\x17\n\x0f\x63ubeWidthExtend\x18\x02 \x01(\x05\x12\x10\n\x08hasAudio\x18\x03 \x01(\x08\x12\x11\n\tpanoWidth\x18\x04 \x01(\x05\x12\x12\n\ndurationMs\x18\x05 \x01(\x01\x12\"\n\tframerate\x18\x06 \x01(\x0b\x32\x0f.bmg.AVRational\"m\n\x10TiledVideoConfig\x12\x14\n\x0csliceOverlap\x18\x01 \x01(\x05\x12\x12\n\nsliceWidth\x18\x02 \x01(\x05\x12/\n\rpyramidLayers\x18\x03 \x03(\x0b\x32\x18.bmg.DynsVideoLayerTiled\"B\n\x15\x42\x61\x63kgroundVideoConfig\x12)\n\x06layers\x18\x01 \x03(\x0b\x32\x19.bmg.DynsVideoLayerNormal\"\xa6\x01\n\nPlayConfig\x12-\n\x0f\x62\x61seVideoConfig\x18\x01 \x01(\x0b\x32\x14.bmg.BaseVideoConfig\x12.\n\x0ftileVideoConfig\x18\x02 \x01(\x0b\x32\x15.bmg.TiledVideoConfig\x12\x39\n\x15\x62\x61\x63kgroundVideoConfig\x18\x03 \x01(\x0b\x32\x1a.bmg.BackgroundVideoConfig\"G\n\x0c\x43ubePlaylist\x12\x12\n\nserverUrls\x18\x01 \x01(\x0c\x12#\n\nplayConfig\x18\x02 \x01(\x0b\x32\x0f.bmg.PlayConfigb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'CubePlaylist_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AVRATIONAL']._serialized_start=27
  _globals['_AVRATIONAL']._serialized_end=65
  _globals['_DYNSVIDEOLAYERTILED']._serialized_start=67
  _globals['_DYNSVIDEOLAYERTILED']._serialized_end=169
  _globals['_DYNSVIDEOLAYERNORMAL']._serialized_start=171
  _globals['_DYNSVIDEOLAYERNORMAL']._serialized_end=265
  _globals['_BASEVIDEOCONFIG']._serialized_start=268
  _globals['_BASEVIDEOCONFIG']._serialized_end=422
  _globals['_TILEDVIDEOCONFIG']._serialized_start=424
  _globals['_TILEDVIDEOCONFIG']._serialized_end=533
  _globals['_BACKGROUNDVIDEOCONFIG']._serialized_start=535
  _globals['_BACKGROUNDVIDEOCONFIG']._serialized_end=601
  _globals['_PLAYCONFIG']._serialized_start=604
  _globals['_PLAYCONFIG']._serialized_end=770
  _globals['_CUBEPLAYLIST']._serialized_start=772
  _globals['_CUBEPLAYLIST']._serialized_end=843
# @@protoc_insertion_point(module_scope)
