# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: extraMediaData.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'extraMediaData.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x65xtraMediaData.proto\x12\x03\x62mg\"g\n\x15\x43ubemapProjectionDesc\x12\x13\n\x0bprojectType\x18\x01 \x01(\x05\x12\x11\n\tpanoWidth\x18\x02 \x01(\x05\x12\x17\n\x0f\x63ubeWidthExtend\x18\x03 \x01(\x05\x12\r\n\x05width\x18\x04 \x01(\x05\"\x1d\n\x0eWideAngleParam\x12\x0b\n\x03\x66ov\x18\x01 \x01(\x01\"\xac\x02\n\x13\x45xtraMediaDataProto\x12\x32\n\x0eprojectionDesc\x18\x01 \x01(\x0b\x32\x1a.bmg.CubemapProjectionDesc\x12+\n\x0ewideAngleParam\x18\x02 \x01(\x0b\x32\x13.bmg.WideAngleParam\x12\x14\n\x0cisCompressed\x18\x03 \x01(\x08\x12\x44\n\x0e\x61\x64\x64itionalData\x18\x04 \x03(\x0b\x32,.bmg.ExtraMediaDataProto.AdditionalDataEntry\x12!\n\tvideoType\x18\x05 \x01(\x0e\x32\x0e.bmg.VideoType\x1a\x35\n\x13\x41\x64\x64itionalDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01*\x92\x01\n\tVideoType\x12\x16\n\x12VIDEOTYPE_ORIGINAL\x10\x00\x12\x13\n\x0fVIDEOTYPE_AGENT\x10\x01\x12\x1b\n\x17VIDEOTYPE_STITCHED_PANO\x10\x02\x12\x17\n\x13VIDEOTYPE_EACUBEMAP\x10\x03\x12\"\n\x1eVIDEOTYPE_CLOUD_SINGLE_FISHEYE\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'extraMediaData_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EXTRAMEDIADATAPROTO_ADDITIONALDATAENTRY']._loaded_options = None
  _globals['_EXTRAMEDIADATAPROTO_ADDITIONALDATAENTRY']._serialized_options = b'8\001'
  _globals['_VIDEOTYPE']._serialized_start=469
  _globals['_VIDEOTYPE']._serialized_end=615
  _globals['_CUBEMAPPROJECTIONDESC']._serialized_start=29
  _globals['_CUBEMAPPROJECTIONDESC']._serialized_end=132
  _globals['_WIDEANGLEPARAM']._serialized_start=134
  _globals['_WIDEANGLEPARAM']._serialized_end=163
  _globals['_EXTRAMEDIADATAPROTO']._serialized_start=166
  _globals['_EXTRAMEDIADATAPROTO']._serialized_end=466
  _globals['_EXTRAMEDIADATAPROTO_ADDITIONALDATAENTRY']._serialized_start=413
  _globals['_EXTRAMEDIADATAPROTO_ADDITIONALDATAENTRY']._serialized_end=466
# @@protoc_insertion_point(module_scope)
