# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: function.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'function.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import attr_value_pb2 as attr__value__pb2
import op_def_pb2 as op__def__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x66unction.proto\x12\x11opencv_tensorflow\x1a\x10\x61ttr_value.proto\x1a\x0cop_def.proto\"x\n\x12\x46unctionDefLibrary\x12\x30\n\x08\x66unction\x18\x01 \x03(\x0b\x32\x1e.opencv_tensorflow.FunctionDef\x12\x30\n\x08gradient\x18\x02 \x03(\x0b\x32\x1e.opencv_tensorflow.GradientDef\"\xb1\x02\n\x0b\x46unctionDef\x12+\n\tsignature\x18\x01 \x01(\x0b\x32\x18.opencv_tensorflow.OpDef\x12\x31\n\x04node\x18\x02 \x03(\x0b\x32#.opencv_tensorflow.FunctionDef.Node\x1a\xc1\x01\n\x04Node\x12\x0b\n\x03ret\x18\x01 \x03(\t\x12\n\n\x02op\x18\x02 \x01(\t\x12\x0b\n\x03\x61rg\x18\x03 \x03(\t\x12\x0b\n\x03\x64\x65p\x18\x04 \x03(\t\x12;\n\x04\x61ttr\x18\x05 \x03(\x0b\x32-.opencv_tensorflow.FunctionDef.Node.AttrEntry\x1aI\n\tAttrEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12+\n\x05value\x18\x02 \x01(\x0b\x32\x1c.opencv_tensorflow.AttrValue:\x02\x38\x01\";\n\x0bGradientDef\x12\x15\n\rfunction_name\x18\x01 \x01(\t\x12\x15\n\rgradient_func\x18\x02 \x01(\tB/\n\x18org.tensorflow.frameworkB\x0e\x46unctionProtosP\x01\xf8\x01\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'function_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\030org.tensorflow.frameworkB\016FunctionProtosP\001\370\001\001'
  _globals['_FUNCTIONDEF_NODE_ATTRENTRY']._loaded_options = None
  _globals['_FUNCTIONDEF_NODE_ATTRENTRY']._serialized_options = b'8\001'
  _globals['_FUNCTIONDEFLIBRARY']._serialized_start=69
  _globals['_FUNCTIONDEFLIBRARY']._serialized_end=189
  _globals['_FUNCTIONDEF']._serialized_start=192
  _globals['_FUNCTIONDEF']._serialized_end=497
  _globals['_FUNCTIONDEF_NODE']._serialized_start=304
  _globals['_FUNCTIONDEF_NODE']._serialized_end=497
  _globals['_FUNCTIONDEF_NODE_ATTRENTRY']._serialized_start=424
  _globals['_FUNCTIONDEF_NODE_ATTRENTRY']._serialized_end=497
  _globals['_GRADIENTDEF']._serialized_start=499
  _globals['_GRADIENTDEF']._serialized_end=558
# @@protoc_insertion_point(module_scope)
