# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: graph.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'graph.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import attr_value_pb2 as attr__value__pb2
import function_pb2 as function__pb2
import versions_pb2 as versions__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bgraph.proto\x12\x11opencv_tensorflow\x1a\x10\x61ttr_value.proto\x1a\x0e\x66unction.proto\x1a\x0eversions.proto\"\xb2\x01\n\x08GraphDef\x12(\n\x04node\x18\x01 \x03(\x0b\x32\x1a.opencv_tensorflow.NodeDef\x12/\n\x08versions\x18\x04 \x01(\x0b\x32\x1d.opencv_tensorflow.VersionDef\x12\x13\n\x07version\x18\x03 \x01(\x05\x42\x02\x18\x01\x12\x36\n\x07library\x18\x02 \x01(\x0b\x32%.opencv_tensorflow.FunctionDefLibrary\"\xc1\x01\n\x07NodeDef\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\n\n\x02op\x18\x02 \x01(\t\x12\r\n\x05input\x18\x03 \x03(\t\x12\x0e\n\x06\x64\x65vice\x18\x04 \x01(\t\x12\x32\n\x04\x61ttr\x18\x05 \x03(\x0b\x32$.opencv_tensorflow.NodeDef.AttrEntry\x1aI\n\tAttrEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12+\n\x05value\x18\x02 \x01(\x0b\x32\x1c.opencv_tensorflow.AttrValue:\x02\x38\x01\x42,\n\x18org.tensorflow.frameworkB\x0bGraphProtosP\x01\xf8\x01\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'graph_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\030org.tensorflow.frameworkB\013GraphProtosP\001\370\001\001'
  _globals['_GRAPHDEF'].fields_by_name['version']._loaded_options = None
  _globals['_GRAPHDEF'].fields_by_name['version']._serialized_options = b'\030\001'
  _globals['_NODEDEF_ATTRENTRY']._loaded_options = None
  _globals['_NODEDEF_ATTRENTRY']._serialized_options = b'8\001'
  _globals['_GRAPHDEF']._serialized_start=85
  _globals['_GRAPHDEF']._serialized_end=263
  _globals['_NODEDEF']._serialized_start=266
  _globals['_NODEDEF']._serialized_end=459
  _globals['_NODEDEF_ATTRENTRY']._serialized_start=386
  _globals['_NODEDEF_ATTRENTRY']._serialized_end=459
# @@protoc_insertion_point(module_scope)
