# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: linkid.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'linkid.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0clinkid.proto\"\x17\n\x07LkidBuf\x12\x0c\n\x04lkid\x18\x01 \x01(\x0c\"*\n\tUploadBuf\x12\x0f\n\x07version\x18\x01 \x01(\r\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"H\n\x07\x44\x65vInfo\x12\x0f\n\x07lkidbuf\x18\x01 \x01(\x0c\x12\x0e\n\x06vender\x18\x02 \x01(\x0c\x12\x0c\n\x04\x66sid\x18\x03 \x01(\x0c\x12\x0e\n\x06\x63\x63\x64\x61ta\x18\x04 \x01(\x0c\x42\x02H\x03')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'linkid_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'H\003'
  _globals['_LKIDBUF']._serialized_start=16
  _globals['_LKIDBUF']._serialized_end=39
  _globals['_UPLOADBUF']._serialized_start=41
  _globals['_UPLOADBUF']._serialized_end=83
  _globals['_DEVINFO']._serialized_start=85
  _globals['_DEVINFO']._serialized_end=157
# @@protoc_insertion_point(module_scope)
