# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: model_state.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'model_state.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11model_state.proto\x12\x11insta360.messages\"\xdb\x01\n\nModelState\x12\x35\n\x04type\x18\x01 \x01(\x0e\x32\'.insta360.messages.ModelState.ValueType\x12\x11\n\tsrcTimeMs\x18\x02 \x01(\x01\x12\x0b\n\x03\x66ov\x18\x03 \x01(\x02\x12\x10\n\x08\x64istance\x18\x04 \x01(\x02\x12\x0c\n\x04quat\x18\x05 \x01(\x0c\x12\x0c\n\x04rect\x18\x06 \x01(\x0c\x12\x0f\n\x07preRoll\x18\x07 \x01(\x02\"7\n\tValueType\x12\n\n\x06normal\x10\x00\x12\x13\n\x0fOnlyOrientation\x10\x01\x12\t\n\x05track\x10\x02\x42\x08\xa2\x02\x05INSPBb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'model_state_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\242\002\005INSPB'
  _globals['_MODELSTATE']._serialized_start=41
  _globals['_MODELSTATE']._serialized_end=260
  _globals['_MODELSTATE_VALUETYPE']._serialized_start=205
  _globals['_MODELSTATE_VALUETYPE']._serialized_end=260
# @@protoc_insertion_point(module_scope)
