# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: move_scene_clip.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'move_scene_clip.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import time_scale_pb2 as time__scale__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15move_scene_clip.proto\x12\x11insta360.messages\x1a\x10time_scale.proto\"f\n\rMoveSceneClip\x12\x12\n\nstart_time\x18\x01 \x01(\x01\x12\x10\n\x08\x65nd_time\x18\x02 \x01(\x01\x12/\n\ttimescale\x18\x03 \x03(\x0b\x32\x1c.insta360.messages.TimeScaleB\x08\xa2\x02\x05INSPBb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'move_scene_clip_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\242\002\005INSPB'
  _globals['_MOVESCENECLIP']._serialized_start=62
  _globals['_MOVESCENECLIP']._serialized_end=164
# @@protoc_insertion_point(module_scope)
