# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: op_def.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'op_def.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import attr_value_pb2 as attr__value__pb2
import types_pb2 as types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cop_def.proto\x12\x11opencv_tensorflow\x1a\x10\x61ttr_value.proto\x1a\x0btypes.proto\"\xe9\x05\n\x05OpDef\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x32\n\tinput_arg\x18\x02 \x03(\x0b\x32\x1f.opencv_tensorflow.OpDef.ArgDef\x12\x33\n\noutput_arg\x18\x03 \x03(\x0b\x32\x1f.opencv_tensorflow.OpDef.ArgDef\x12.\n\x04\x61ttr\x18\x04 \x03(\x0b\x32 .opencv_tensorflow.OpDef.AttrDef\x12\x35\n\x0b\x64\x65precation\x18\x08 \x01(\x0b\x32 .opencv_tensorflow.OpDeprecation\x12\x0f\n\x07summary\x18\x05 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x06 \x01(\t\x12\x16\n\x0eis_commutative\x18\x12 \x01(\x08\x12\x14\n\x0cis_aggregate\x18\x10 \x01(\x08\x12\x13\n\x0bis_stateful\x18\x11 \x01(\x08\x12\"\n\x1a\x61llows_uninitialized_input\x18\x13 \x01(\x08\x1a\xa6\x01\n\x06\x41rgDef\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12)\n\x04type\x18\x03 \x01(\x0e\x32\x1b.opencv_tensorflow.DataType\x12\x11\n\ttype_attr\x18\x04 \x01(\t\x12\x13\n\x0bnumber_attr\x18\x05 \x01(\t\x12\x16\n\x0etype_list_attr\x18\x06 \x01(\t\x12\x0e\n\x06is_ref\x18\x10 \x01(\x08\x1a\xcb\x01\n\x07\x41ttrDef\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x33\n\rdefault_value\x18\x03 \x01(\x0b\x32\x1c.opencv_tensorflow.AttrValue\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12\x13\n\x0bhas_minimum\x18\x05 \x01(\x08\x12\x0f\n\x07minimum\x18\x06 \x01(\x03\x12\x34\n\x0e\x61llowed_values\x18\x07 \x01(\x0b\x32\x1c.opencv_tensorflow.AttrValue\"5\n\rOpDeprecation\x12\x0f\n\x07version\x18\x01 \x01(\x05\x12\x13\n\x0b\x65xplanation\x18\x02 \x01(\t\".\n\x06OpList\x12$\n\x02op\x18\x01 \x03(\x0b\x32\x18.opencv_tensorflow.OpDefB,\n\x18org.tensorflow.frameworkB\x0bOpDefProtosP\x01\xf8\x01\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'op_def_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\030org.tensorflow.frameworkB\013OpDefProtosP\001\370\001\001'
  _globals['_OPDEF']._serialized_start=67
  _globals['_OPDEF']._serialized_end=812
  _globals['_OPDEF_ARGDEF']._serialized_start=440
  _globals['_OPDEF_ARGDEF']._serialized_end=606
  _globals['_OPDEF_ATTRDEF']._serialized_start=609
  _globals['_OPDEF_ATTRDEF']._serialized_end=812
  _globals['_OPDEPRECATION']._serialized_start=814
  _globals['_OPDEPRECATION']._serialized_end=867
  _globals['_OPLIST']._serialized_start=869
  _globals['_OPLIST']._serialized_end=915
# @@protoc_insertion_point(module_scope)
