# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pano_trans_plus.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'pano_trans_plus.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import basic_info_pb2 as basic__info__pb2
import time_position_pb2 as time__position__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15pano_trans_plus.proto\x12\x11insta360.messages\x1a\x10\x62\x61sic_info.proto\x1a\x13time_position.proto\"\xfd\x04\n\rPanoTransPlus\x12\x0e\n\x06isYFov\x18\x01 \x01(\x08\x12\x0e\n\x06\x61spect\x18\x02 \x01(\x01\x12\x36\n\rbeginPosition\x18\x03 \x01(\x0b\x32\x1f.insta360.messages.TimePosition\x12\x34\n\x0b\x65ndPosition\x18\x04 \x01(\x0b\x32\x1f.insta360.messages.TimePosition\x12>\n\nlayer_info\x18\x05 \x01(\x0b\x32*.insta360.messages.PanoTransPlus.LayerInfo\x1a\x9d\x03\n\tLayerInfo\x12\x0f\n\x07version\x18\x01 \x01(\t\x12\x12\n\nisDuration\x18\x02 \x01(\x08\x12\x1a\n\x12start_timestamp_ms\x18\x03 \x01(\x01\x12\x18\n\x10\x65nd_timestamp_ms\x18\x04 \x01(\x01\x12\x14\n\x0cturningPoint\x18\x05 \x01(\x01\x12\x34\n\rcamera_states\x18\x06 \x03(\x0b\x32\x1d.insta360.messages.CameraInfo\x12\x34\n\robject_states\x18\x07 \x03(\x0b\x32\x1d.insta360.messages.ObjectInfo\x12:\n\x12\x63\x61mera_transitions\x18\x08 \x03(\x0b\x32\x1e.insta360.messages.BezierCubic\x12:\n\x12object_transitions\x18\t \x03(\x0b\x32\x1e.insta360.messages.BezierCubic\x12;\n\x0f\x61lphaTransition\x18\n \x01(\x0b\x32\".insta360.messages.AlphaTransitionB\x08\xa2\x02\x05INSPBb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pano_trans_plus_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\242\002\005INSPB'
  _globals['_PANOTRANSPLUS']._serialized_start=84
  _globals['_PANOTRANSPLUS']._serialized_end=721
  _globals['_PANOTRANSPLUS_LAYERINFO']._serialized_start=308
  _globals['_PANOTRANSPLUS_LAYERINFO']._serialized_end=721
# @@protoc_insertion_point(module_scope)
