# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: section.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'section.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import model_state_pb2 as model__state__pb2
import time_position_pb2 as time__position__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rsection.proto\x12\x11insta360.messages\x1a\x11model_state.proto\x1a\x13time_position.proto\"\xa8\x01\n\x07Section\x12/\n\x08srcState\x18\x01 \x03(\x0b\x32\x1d.insta360.messages.ModelState\x12\x36\n\rbeginPosition\x18\x02 \x01(\x0b\x32\x1f.insta360.messages.TimePosition\x12\x34\n\x0b\x65ndPosition\x18\x03 \x01(\x0b\x32\x1f.insta360.messages.TimePositionB\x08\xa2\x02\x05INSPBb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'section_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\242\002\005INSPB'
  _globals['_SECTION']._serialized_start=77
  _globals['_SECTION']._serialized_end=245
# @@protoc_insertion_point(module_scope)
