# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: snap.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'snap.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nsnap.proto\x12\x11insta360.messages\"\xb7\x03\n\x10SnapUnsmoothData\x12\x16\n\x0e\x64\x65vice_time_ms\x18\x01 \x01(\x01\x12\x15\n\rframe_time_ms\x18\x02 \x01(\x01\x12\x0b\n\x03yaw\x18\x03 \x01(\x02\x12\x0c\n\x04roll\x18\x04 \x01(\x02\x12\r\n\x05pitch\x18\x05 \x01(\x02\x12\x0b\n\x03\x66ov\x18\x06 \x01(\x02\x12\x10\n\x08\x64istance\x18\x07 \x01(\x02\x12:\n\x04mode\x18\x08 \x01(\x0e\x32,.insta360.messages.SnapUnsmoothData.SnapMode\x12\x13\n\x0bsrc_time_ms\x18\t \x01(\x01\x12\x0f\n\x07version\x18\n \x01(\t\"\xc8\x01\n\x08SnapMode\x12\x1d\n\x19head_tracker_plus_gesture\x10\x00\x12\x15\n\x11\x66orward_direction\x10\x01\x12\x0f\n\x0bhero_follow\x10\x02\x12\x12\n\x0epanoramic_view\x10\x03\x12\x0c\n\x08joystick\x10\x04\x12\x0f\n\x0b\x64\x65\x65ptracker\x10\x05\x12\x16\n\x12surround_180_right\x10\x06\x12\x15\n\x11surround_180_left\x10\x07\x12\x13\n\x0f\x61steroid_rotate\x10\x08\"K\n\x08SnapData\x12?\n\x12snap_unsmooth_data\x18\x01 \x03(\x0b\x32#.insta360.messages.SnapUnsmoothDataB\x08\xa2\x02\x05INSPBb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'snap_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\242\002\005INSPB'
  _globals['_SNAPUNSMOOTHDATA']._serialized_start=34
  _globals['_SNAPUNSMOOTHDATA']._serialized_end=473
  _globals['_SNAPUNSMOOTHDATA_SNAPMODE']._serialized_start=273
  _globals['_SNAPUNSMOOTHDATA_SNAPMODE']._serialized_end=473
  _globals['_SNAPDATA']._serialized_start=475
  _globals['_SNAPDATA']._serialized_end=550
# @@protoc_insertion_point(module_scope)
