# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: strange_section.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'strange_section.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import model_state_pb2 as model__state__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15strange_section.proto\x12\x11insta360.messages\x1a\x11model_state.proto\"|\n\x0eStrangeSection\x12/\n\x08srcState\x18\x01 \x03(\x0b\x32\x1d.insta360.messages.ModelState\x12\x15\n\rbeginPosition\x18\x02 \x01(\x01\x12\x13\n\x0b\x65ndPosition\x18\x03 \x01(\x01\x12\r\n\x05pitch\x18\x04 \x01(\x02\x42\x08\xa2\x02\x05INSPBb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'strange_section_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\242\002\005INSPB'
  _globals['_STRANGESECTION']._serialized_start=63
  _globals['_STRANGESECTION']._serialized_end=187
# @@protoc_insertion_point(module_scope)
