# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tensor.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'tensor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import tensor_shape_pb2 as tensor__shape__pb2
import types_pb2 as types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ctensor.proto\x12\x11opencv_tensorflow\x1a\x12tensor_shape.proto\x1a\x0btypes.proto\"\xf3\x02\n\x0bTensorProto\x12*\n\x05\x64type\x18\x01 \x01(\x0e\x32\x1b.opencv_tensorflow.DataType\x12\x39\n\x0ctensor_shape\x18\x02 \x01(\x0b\x32#.opencv_tensorflow.TensorShapeProto\x12\x16\n\x0eversion_number\x18\x03 \x01(\x05\x12\x16\n\x0etensor_content\x18\x04 \x01(\x0c\x12\x14\n\x08half_val\x18\r \x03(\x05\x42\x02\x10\x01\x12\x15\n\tfloat_val\x18\x05 \x03(\x02\x42\x02\x10\x01\x12\x16\n\ndouble_val\x18\x06 \x03(\x01\x42\x02\x10\x01\x12\x13\n\x07int_val\x18\x07 \x03(\x05\x42\x02\x10\x01\x12\x12\n\nstring_val\x18\x08 \x03(\x0c\x12\x18\n\x0cscomplex_val\x18\t \x03(\x02\x42\x02\x10\x01\x12\x15\n\tint64_val\x18\n \x03(\x03\x42\x02\x10\x01\x12\x14\n\x08\x62ool_val\x18\x0b \x03(\x08\x42\x02\x10\x01\x12\x18\n\x0c\x64\x63omplex_val\x18\x0c \x03(\x01\x42\x02\x10\x01\x42-\n\x18org.tensorflow.frameworkB\x0cTensorProtosP\x01\xf8\x01\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tensor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\030org.tensorflow.frameworkB\014TensorProtosP\001\370\001\001'
  _globals['_TENSORPROTO'].fields_by_name['half_val']._loaded_options = None
  _globals['_TENSORPROTO'].fields_by_name['half_val']._serialized_options = b'\020\001'
  _globals['_TENSORPROTO'].fields_by_name['float_val']._loaded_options = None
  _globals['_TENSORPROTO'].fields_by_name['float_val']._serialized_options = b'\020\001'
  _globals['_TENSORPROTO'].fields_by_name['double_val']._loaded_options = None
  _globals['_TENSORPROTO'].fields_by_name['double_val']._serialized_options = b'\020\001'
  _globals['_TENSORPROTO'].fields_by_name['int_val']._loaded_options = None
  _globals['_TENSORPROTO'].fields_by_name['int_val']._serialized_options = b'\020\001'
  _globals['_TENSORPROTO'].fields_by_name['scomplex_val']._loaded_options = None
  _globals['_TENSORPROTO'].fields_by_name['scomplex_val']._serialized_options = b'\020\001'
  _globals['_TENSORPROTO'].fields_by_name['int64_val']._loaded_options = None
  _globals['_TENSORPROTO'].fields_by_name['int64_val']._serialized_options = b'\020\001'
  _globals['_TENSORPROTO'].fields_by_name['bool_val']._loaded_options = None
  _globals['_TENSORPROTO'].fields_by_name['bool_val']._serialized_options = b'\020\001'
  _globals['_TENSORPROTO'].fields_by_name['dcomplex_val']._loaded_options = None
  _globals['_TENSORPROTO'].fields_by_name['dcomplex_val']._serialized_options = b'\020\001'
  _globals['_TENSORPROTO']._serialized_start=69
  _globals['_TENSORPROTO']._serialized_end=440
# @@protoc_insertion_point(module_scope)
