# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: timeshfit4_animation.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'timeshfit4_animation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import section_pb2 as section__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1atimeshfit4_animation.proto\x12\x11insta360.messages\x1a\rsection.proto\"\xa7\x01\n\x0b\x43onfigParam\x12\x14\n\x0c\x64iscreteMode\x18\x01 \x01(\x08\x12\x16\n\x0e\x64\x65\x62ugLogEnable\x18\x02 \x01(\x08\x12\x14\n\x0c\x64\x65\x62ugLogPath\x18\x03 \x01(\x0c\x12\x17\n\x0f\x64\x65\x66\x61ultDistance\x18\x04 \x01(\x01\x12\x12\n\ndefaultFov\x18\x05 \x01(\x01\x12\x11\n\ttargetFov\x18\x06 \x01(\x01\x12\x14\n\x0ctargetMinFov\x18\x07 \x01(\x01\")\n\x08PairData\x12\r\n\x05\x66irst\x18\x01 \x01(\x01\x12\x0e\n\x06second\x18\x02 \x01(\x01\"\xf8\x02\n\nDataSource\x12\x12\n\nidentifier\x18\x01 \x01(\x0c\x12\x15\n\rvideoDuration\x18\x02 \x01(\x01\x12\x32\n\x0e\x66orwardSection\x18\x03 \x01(\x0b\x32\x1a.insta360.messages.Section\x12\x34\n\x10saliencySections\x18\x04 \x03(\x0b\x32\x1a.insta360.messages.Section\x12\x32\n\x0eupviewSections\x18\x05 \x03(\x0b\x32\x1a.insta360.messages.Section\x12\x35\n\x11symmetricSections\x18\x06 \x03(\x0b\x32\x1a.insta360.messages.Section\x12\x30\n\x0bstillRegion\x18\x07 \x03(\x0b\x32\x1b.insta360.messages.PairData\x12\x38\n\x13timelapseSpeedPoint\x18\x08 \x03(\x0b\x32\x1b.insta360.messages.PairData\"y\n\x13TimeShift4Animation\x12.\n\x06\x63onfig\x18\x01 \x01(\x0b\x32\x1e.insta360.messages.ConfigParam\x12\x32\n\x0b\x64\x61taSources\x18\x02 \x03(\x0b\x32\x1d.insta360.messages.DataSourceB\x08\xa2\x02\x05INSPBb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'timeshfit4_animation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\242\002\005INSPB'
  _globals['_CONFIGPARAM']._serialized_start=65
  _globals['_CONFIGPARAM']._serialized_end=232
  _globals['_PAIRDATA']._serialized_start=234
  _globals['_PAIRDATA']._serialized_end=275
  _globals['_DATASOURCE']._serialized_start=278
  _globals['_DATASOURCE']._serialized_end=654
  _globals['_TIMESHIFT4ANIMATION']._serialized_start=656
  _globals['_TIMESHIFT4ANIMATION']._serialized_end=777
# @@protoc_insertion_point(module_scope)
