# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tracker_animation.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'tracker_animation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import tracker_section_pb2 as tracker__section__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17tracker_animation.proto\x12\x11insta360.messages\x1a\x15tracker_section.proto\"F\n\x10TrackerAnimation\x12\x32\n\x07section\x18\x01 \x01(\x0b\x32!.insta360.messages.TrackerSectionB\x08\xa2\x02\x05INSPBb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tracker_animation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\242\002\005INSPB'
  _globals['_TRACKERANIMATION']._serialized_start=69
  _globals['_TRACKERANIMATION']._serialized_end=139
# @@protoc_insertion_point(module_scope)
